workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - smitpatdiya7452@gmail.com

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build iOS IPA (No-Sign Package)
        script: |
          # Flutter will automatically generate the Podfile and run pod install during build
          flutter build ios --release --no-codesign
          mkdir -p build/ios/iphoneos/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload
          cd build/ios/iphoneos && zip -r vdandsons_app.ipa Payload
    artifacts:
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - smitpatdiya7452@gmail.com
