workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - firebase_credentials # Optional: Add your firebase related env vars here
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - user@example.com # Update with your email

  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS IPA
        script: flutter build ipa --release --no-codesign # Change to your signing requirements
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com # Update with your email
